version: 2.1

jobs:
  linux-gcc:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run:
          name: Install Software
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
            sudo apt-get install -y libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev
            sudo apt-get update
      - run: ./contrib/install_db4.sh `pwd`
      - run: ./autogen.sh
      - run:
          name: Configure
          command: |
            export BDB_PREFIX=`pwd`'/db4' && ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
      - run: make -j 4
      - run: make check -j 4

workflows:
  version: 2
  run-all:
    jobs:
      - linux-gcc
